### Get JWT Token
GET http://localhost:5500
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMDk3OTU0MTkzMjY0Nzc4MDk3NjMiLCJlbWFpbCI6Imtib3JiYW5vQHVwLmVkdS5waCIsIm5hbWUiOiJLaW50IExvdWlzZSBCb3JiYW5vIiwiaWF0IjoxNzczNjcyNzg4LCJleHAiOjE3NzM2NzM2ODh9.54u6B4oNBZnbl0D8P9Gks5YMOlE7U-iziqzqZ1t_t1g

### Create Task (broadcasts to WebSocket clients)
POST http://localhost:8000/task/add
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMDk3OTU0MTkzMjY0Nzc4MDk3NjMiLCJlbWFpbCI6Imtib3JiYW5vQHVwLmVkdS5waCIsIm5hbWUiOiJLaW50IExvdWlzZSBCb3JiYW5vIiwiaWF0IjoxNzczNjcyNzg4LCJleHAiOjE3NzM2NzM2ODh9.54u6B4oNBZnbl0D8P9Gks5YMOlE7U-iziqzqZ1t_t1g

{
  "title": "Test Task",
  "details": "Testing broadcast",
  "current_status": "todo"
}